FORMAT: 1A

# ControlPanel - Status

This section is a API allowing get server status.

## Status API Root [/public/status]

## Status Server [GET]
+ Response 200 (application/json)
    {
        'Server OK'
    }

    